### ISSUE TITLE
`bloop` manifest will break `git`

### ISSUE THREAD

**Issue by niheaven** [scalacenter/scoop-bloop#3]
Why `bloop` use `$HOME` env var? This will break `git` that it will search for `.ssh` and `.gitconfig` in `$HOME`...

**Comment by 4lex1v** [comment]
What's the `HOME` variable is used for? Any chance it could be rename to `BLOOP_HOME`. Setting it globally to bloop's folder is a bit controversial decision.

**Comment by niheaven** [comment]
`git` in Windows will search `$HOME` for its config if it was set. If there is not `$HOME`, `git` search them in `$USERPROFILE` (`$USERPROFILE/.ssh`). But if there is `$HOME`, it search them there (`$HOME/.ssh`) and reports errors.

**Comment by 4lex1v** [comment]
I mean i have the same issue, though not only with git, but other things as well. Hence my question if it's possible to rename the var to `BLOOP_HOME`.

**Comment by nightscape** [comment]
Created a PR and posted on Twitter: https://twitter.com/gimme_moe/status/1183743139829469185

**Comment by jvican** [comment]
Closing out of inactivity. This issue is most likely gone now that we've changed the way we install bloop through scoop
