### ISSUE TITLE
Windows paths with spaces not supported

### ISSUE THREAD

**Issue by er1c** [scalacenter/scoop-bloop#5]
```
PS C:\Users\Eric Peters> bloop about
C:\Users\Eric Peters\scoop\apps\python\current\python.exe: can't find '__main__' module in 'C:\\Users\\Eric'
```

Looks like something isn't quoted properly to handle paths with spaces.

**original bloop.cmd**

```
@echo off
python C:\Users\Eric Peters\scoop\apps\bloop\1.3.4\bloop %*
```

**Changing to**

```
@echo off
python "C:\Users\Eric Peters\scoop\apps\bloop\1.3.4\bloop" %*`
```

Fixes the problem, I'm not entirely sure where this file is coming from/how it is generated.

**Version** `scoop install bloop` - `1.3.4`

**Comment by jvican** [comment]
Would you mind sending a PR to fix this @er1c ? Sorry, I didn't get to see this ticket.

**Comment by er1c** [comment]
@jvican I'm not actually sure howto fix it

**Comment by er1c** [comment]
Hmm looks like it's from: https://github.com/scalacenter/bloop/releases/download/v1.4.0-RC1/install.py

**Comment by er1c** [comment]
Added https://github.com/scalacenter/bloop/pull/1131
